#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import math
import re
import statistics
import csv
from decimal import Decimal, ROUND_HALF_UP
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parent.parent
DATASETS_ROOT = ROOT / "datasets"
DATASET_DIR = DATASETS_ROOT / "appendix_a"
APPENDIX_B_DIR = DATASETS_ROOT / "appendix_b"
APPENDIX_B_ALT_DIR = DATASETS_ROOT / "appendex_b"
GENERATED_DIR = ROOT / "generated"
MANIFEST_FILE = GENERATED_DIR / ".dataset_manifest.sha256"
APPENDIX_TEX = GENERATED_DIR / "appendix_a_include.tex"
CORR_TEX = GENERATED_DIR / "correlation_data.tex"
APPENDIX_B_TEX = GENERATED_DIR / "appendix_b_model_summary.tex"

TEST_HEADER_RE = re.compile(r"^--Test(\d+)--\s*$")
BIT_LINE_RE = re.compile(
    r"^\[(R\d+)\]\s+bit(\d+):\s+p1=([0-9.]+)\s+bias=([0-9.]+)\s+trans=([0-9.]+)\s+mono_z=([0-9.]+)\s+runs_z=([0-9A-Za-z.+-]+)\s*$"
)


@dataclass
class BitStat:
    bit: int
    p1: float


@dataclass
class TestBlock:
    index: int
    groups: Dict[str, Dict[int, BitStat]]


@dataclass
class PairRow:
    test_label: str
    bit: int
    p_in: float
    p_out: float
    k_raw: float


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def manifest_hash(dataset_dirs: List[Path]) -> str:
    h = hashlib.sha256()
    h.update(b"generate_docs_data_v1\n")
    for dataset_dir in dataset_dirs:
        if not dataset_dir.exists():
            continue
        root_label = dataset_dir.name
        for p in sorted(dataset_dir.rglob("*")):
            if p.is_dir():
                continue
            rel = p.relative_to(dataset_dir).as_posix()
            h.update(root_label.encode("utf-8"))
            h.update(b":")
            h.update(rel.encode("utf-8"))
            h.update(b"\0")
            h.update(sha256_file(p).encode("ascii"))
            h.update(b"\n")
    return h.hexdigest()


def language_for(path: Path) -> str:
    ext = path.suffix.lower()
    return {
        ".tex": "tex",
        ".c": "c",
        ".h": "c",
        ".asm": "tasm",
        ".inc": "tasm",
        ".py": "python",
        ".json": "json",
        ".csv": "text",
        ".dat": "text",
        ".txt": "text",
        ".md": "text",
    }.get(ext, "text")


def tex_escape(s: str) -> str:
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("#", "\\#")
        .replace("{", "\\{")
        .replace("}", "\\}")
    )


def build_appendix_include(dataset_dir: Path) -> str:
    files = [p for p in sorted(dataset_dir.rglob("*")) if p.is_file()]
    out: List[str] = []
    out.append("% auto-generated by scripts/generate_docs_data.py")
    if not files:
        out.append("\\section*{No dataset files found}")
        out.append("No files were found in \\texttt{datasets/appendix\\_a} at build time.")
        return "\n".join(out) + "\n"

    out.append("\\section*{Dataset File Index}")
    out.append("\\begin{itemize}")
    for p in files:
        rel = p.relative_to(ROOT).as_posix()
        out.append(f"  \\item \\texttt{{{tex_escape(rel)}}}")
    out.append("\\end{itemize}")

    for p in files:
        rel = p.relative_to(ROOT).as_posix()
        lang = language_for(p)
        title = p.relative_to(dataset_dir).as_posix()
        out.append("")
        out.append(f"\\section*{{\\texttt{{{tex_escape(title)}}}}}")
        out.append("\\inputminted[")
        out.append("  breaklines,")
        out.append("  breakanywhere,")
        out.append("  fontsize=\\footnotesize")
        out.append(f"]{{{lang}}}{{{rel}}}")

    return "\n".join(out) + "\n"


def parse_entropy_runs(dat_path: Path) -> List[TestBlock]:
    if not dat_path.exists():
        return []

    blocks: List[TestBlock] = []
    current: TestBlock | None = None

    with dat_path.open("r", encoding="utf-8", errors="replace") as f:
        for raw in f:
            line = raw.strip()
            if not line:
                continue

            m = TEST_HEADER_RE.match(line)
            if m:
                current = TestBlock(index=int(m.group(1)), groups={})
                blocks.append(current)
                continue

            if current is None:
                continue

            m = BIT_LINE_RE.match(line)
            if not m:
                continue

            grp = m.group(1)
            bit = int(m.group(2))
            p1 = float(m.group(3))
            current.groups.setdefault(grp, {})[bit] = BitStat(bit=bit, p1=p1)

    return blocks


def choose_best_pair(block: TestBlock) -> PairRow | None:
    g0 = block.groups.get("R0", {})
    g17 = block.groups.get("R17", {})
    common_bits = sorted(set(g0.keys()) & set(g17.keys()))
    if not common_bits:
        return None

    best_bit = min(common_bits, key=lambda b: (abs(g17[b].p1 - 0.5), abs(g0[b].p1 - 0.5), b))
    p_in = g0[best_bit].p1
    p_out = g17[best_bit].p1
    k_raw = k_inversion(n=17.0, p_in=p_in, p_out=p_out)
    return PairRow(test_label=f"test{block.index}", bit=best_bit, p_in=p_in, p_out=p_out, k_raw=k_raw)


def k_inversion(n: float, p_in: float, p_out: float) -> float:
    a = abs(1.0 - 2.0 * p_in)
    b = abs(1.0 - 2.0 * p_out)
    if a <= 0.0 or b <= 0.0:
        return 17.0
    den = math.log(b)
    if abs(den) < 1e-15:
        return 17.0
    val = n * math.log(a) / den
    if val < 1.0:
        val = 1.0
    if val > 17.0:
        val = 17.0
    return val


def tukey_quartiles(vals: List[float]) -> Tuple[float, float]:
    s = sorted(vals)
    n = len(s)
    if n == 1:
        return s[0], s[0]
    if n % 2 == 1:
        lower = s[: n // 2]
        upper = s[n // 2 + 1 :]
    else:
        lower = s[: n // 2]
        upper = s[n // 2 :]

    def med(a: List[float]) -> float:
        m = len(a)
        if m == 0:
            return s[0]
        if m % 2 == 1:
            return a[m // 2]
        return (a[m // 2 - 1] + a[m // 2]) / 2.0

    return med(lower), med(upper)


def fmt(x: float, digits: int = 4) -> str:
    return f"{x:.{digits}f}"


def fmt_half_up(x: float, digits: int) -> str:
    quant = Decimal("1." + ("0" * digits))
    return format(Decimal(str(x)).quantize(quant, rounding=ROUND_HALF_UP), f".{digits}f")


def fold_p(p: float) -> float:
    return max(p, 1.0 - p)


def build_correlation_macros(dataset_dir: Path) -> str:
    dat = dataset_dir / "entropy_runs.dat"
    blocks = parse_entropy_runs(dat)
    pairs_all = [p for p in (choose_best_pair(b) for b in blocks) if p is not None]
    display_limit = 9
    pairs = pairs_all[:display_limit]

    out: List[str] = []
    out.append("% auto-generated by scripts/generate_docs_data.py")

    xor_reads = 17
    pool_bytes = 119
    output_bits = 64
    p_worst = 0.7500

    if not pairs_all:
        out.append("\\newcommand{\\CalibRunRows}{test1 & 5 & 0.7500 & 0.5000 & 0.0000 \\\\}")
        out.append("\\newcommand{\\CalibLineSegments}{\\draw[blue!60,opacity=0.8] (1,0.75) -- (2,0.50);}")
        out.append("\\newcommand{\\CalibPointFills}{\\filldraw[blue!80] (1,0.75) circle (0.7pt); \\filldraw[blue!80] (2,0.50) circle (0.7pt);}")
        out.append("\\newcommand{\\CalibKRows}{test1-bit5 & 0.7500 & 0.5000 & 1.000 \\\\}")
        out.append("\\newcommand{\\CalibKMedian}{1.000}")
        out.append("\\newcommand{\\CalibKMean}{1.000}")
        out.append("\\newcommand{\\CalibKSigma}{0.000}")
        out.append("\\newcommand{\\CalibKQOne}{1.000}")
        out.append("\\newcommand{\\CalibKQThree}{1.000}")
        out.append("\\newcommand{\\CalibKIQR}{0.000}")
        out.append("\\newcommand{\\CalibRangeLow}{1.000}")
        out.append("\\newcommand{\\CalibRangeHigh}{1.000}")
        out.append("\\newcommand{\\CalibWorkingK}{1.000}")
        out.append("\\newcommand{\\CalibBiasRZero}{0.2500}")
        out.append("\\newcommand{\\CalibBiasRSeventeen}{0.0000}")
        out.append("\\newcommand{\\CalibYTicks}{\\foreach \\yy/\\lbl in {1/1,2/2,3/3,4/4,5/5,6/6}{\\draw (0.65,\\yy) -- (0.75,\\yy);\\node[left] at (0.65,\\yy) {\\scriptsize \\lbl};}}")
        out.append("\\newcommand{\\CalibKPath}{(1,1.000)}")
        out.append("\\newcommand{\\CalibKPointFills}{\\filldraw[blue!85] (1,1.000) circle (0.8pt);}")
        out.append("\\newcommand{\\CalibXAxisMax}{5.6}")
        out.append("\\newcommand{\\CalibXAxisLabel}{5.65}")
        out.append("\\newcommand{\\CalibXTicks}{\\draw (1,0.55) -- (1,0.65);\\node[below] at (1,0.55) {\\scriptsize 1};}")
        out.append(f"\\newcommand{{\\CalibXorReads}}{{{xor_reads}}}")
        out.append(f"\\newcommand{{\\CalibPoolBytes}}{{{pool_bytes}}}")
        out.append(f"\\newcommand{{\\CalibOutputBits}}{{{output_bits}}}")
        out.append(f"\\newcommand{{\\CalibPWorst}}{{{p_worst:.4f}}}")
        out.append("\\newcommand{\\CalibNeffByte}{17}")
        out.append("\\newcommand{\\CalibNeffPool}{2023}")
        out.append("\\newcommand{\\CalibPOutByte}{0.50000}")
        out.append("\\newcommand{\\CalibPOutPool}{0.50000}")
        out.append("\\newcommand{\\CalibMinEntropyBit}{1.00000}")
        out.append("\\newcommand{\\CalibMinEntropyOutput}{1.00000}")
        out.append("\\newcommand{\\CalibDisplayCount}{1}")
        out.append("\\newcommand{\\CalibTotalCount}{1}")
        out.append("\\newcommand{\\CalibTruncatedNote}{}")
        return "\n".join(out) + "\n"

    run_rows = []
    line_cmds = []
    point_cmds = []
    k_rows = []
    k_vals = []
    bias_r0 = []
    bias_r17 = []

    for p in pairs:
        p_in_fold = fold_p(p.p_in)
        p_out_fold = fold_p(p.p_out)
        run_rows.append(f"{p.test_label} & {p.bit} & {fmt(p_in_fold)} & {fmt(p_out_fold)} & {fmt(abs(p_out_fold-0.5))} \\\\")
        line_cmds.append(f"\\draw[blue!60,opacity=0.8] (1,{fmt(p_in_fold)}) -- (2,{fmt(p_out_fold)});")
        point_cmds.append(f"\\filldraw[blue!80] (1,{fmt(p_in_fold)}) circle (0.7pt); \\filldraw[blue!80] (2,{fmt(p_out_fold)}) circle (0.7pt);")
        k_rows.append(f"{p.test_label}-bit{p.bit} & {fmt(p.p_in)} & {fmt(p.p_out)} & {p.k_raw:.3f} \\\\")

    for p in pairs_all:
        k_vals.append(p.k_raw)
        bias_r0.append(abs(p.p_in - 0.5))
        bias_r17.append(abs(p.p_out - 0.5))

    # Keep summary stats consistent with the displayed 3-decimal k rows.
    ks = sorted(float(fmt_half_up(v, 3)) for v in k_vals)
    k_median = statistics.median(ks)
    k_mean = statistics.mean(ks)
    k_sigma = statistics.pstdev(ks) if len(ks) > 1 else 0.0
    k_q1, k_q3 = tukey_quartiles(ks)
    k_iqr = k_q3 - k_q1
    k_low = min(ks)
    k_high = max(ks)

    y_max = max(6, int(math.ceil(k_high)))
    y_tick_parts = []
    for y in range(1, y_max + 1):
        y_tick_parts.append(
            f"\\draw (0.65,{y}) -- (0.75,{y});\\node[left] at (0.65,{y}) {{\\scriptsize {y}}};"
        )

    x_tick_parts = []
    for i in range(1, len(pairs) + 1):
        x_tick_parts.append(
            f"\\draw ({i},0.55) -- ({i},0.65);\\node[below] at ({i},0.55) {{\\scriptsize {i}}};"
        )

    k_path = " -- ".join(f"({i},{pairs[i-1].k_raw:.3f})" for i in range(1, len(pairs) + 1))
    k_points = "\n".join(
        f"\\filldraw[blue!85] ({i},{pairs[i-1].k_raw:.3f}) circle (0.8pt);" for i in range(1, len(pairs) + 1)
    )

    out.append(f"\\newcommand{{\\CalibRunRows}}{{{' '.join(run_rows)}}}")
    out.append(f"\\newcommand{{\\CalibLineSegments}}{{{' '.join(line_cmds)}}}")
    out.append(f"\\newcommand{{\\CalibPointFills}}{{{' '.join(point_cmds)}}}")
    out.append(f"\\newcommand{{\\CalibKRows}}{{{' '.join(k_rows)}}}")
    out.append(f"\\newcommand{{\\CalibKMedian}}{{{fmt_half_up(k_median, 3)}}}")
    out.append(f"\\newcommand{{\\CalibKMean}}{{{fmt_half_up(k_mean, 3)}}}")
    out.append(f"\\newcommand{{\\CalibKSigma}}{{{fmt_half_up(k_sigma, 3)}}}")
    out.append(f"\\newcommand{{\\CalibKQOne}}{{{fmt_half_up(k_q1, 3)}}}")
    out.append(f"\\newcommand{{\\CalibKQThree}}{{{fmt_half_up(k_q3, 3)}}}")
    out.append(f"\\newcommand{{\\CalibKIQR}}{{{fmt_half_up(k_iqr, 3)}}}")
    out.append(f"\\newcommand{{\\CalibRangeLow}}{{{fmt_half_up(k_low, 3)}}}")
    out.append(f"\\newcommand{{\\CalibRangeHigh}}{{{fmt_half_up(k_high, 3)}}}")
    out.append(f"\\newcommand{{\\CalibWorkingK}}{{{fmt_half_up(k_median, 3)}}}")
    out.append(f"\\newcommand{{\\CalibBiasRZero}}{{{statistics.mean(bias_r0):.4f}}}")
    out.append(f"\\newcommand{{\\CalibBiasRSeventeen}}{{{statistics.mean(bias_r17):.4f}}}")
    out.append(f"\\newcommand{{\\CalibYTicks}}{{{''.join(y_tick_parts)}}}")
    out.append(f"\\newcommand{{\\CalibKPath}}{{{k_path}}}")
    out.append("\\newcommand{\\CalibKPointFills}{" + k_points.replace("\n", " ") + "}")
    out.append(f"\\newcommand{{\\CalibXAxisMax}}{{{len(pairs)+0.6:.1f}}}")
    out.append(f"\\newcommand{{\\CalibXAxisLabel}}{{{len(pairs)+0.65:.2f}}}")
    out.append(f"\\newcommand{{\\CalibXTicks}}{{{''.join(x_tick_parts)}}}")

    k_working = round(k_median, 3)
    n_eff_byte = int(math.floor(xor_reads / k_working)) if k_working > 0 else xor_reads
    if n_eff_byte < 1:
        n_eff_byte = 1
    n_eff_pool = int(math.floor((xor_reads * pool_bytes) / k_working)) if k_working > 0 else xor_reads * pool_bytes
    if n_eff_pool < 1:
        n_eff_pool = 1

    def p_xor(p: float, n: int) -> float:
        return (1.0 - ((1.0 - 2.0 * p) ** n)) / 2.0

    p_out_byte = p_xor(p_worst, n_eff_byte)
    p_out_pool = p_xor(p_worst, n_eff_pool)
    h_inf_bit = -math.log2(max(p_out_byte, 1.0 - p_out_byte))
    h_inf_out = -math.log2(max(p_out_pool, 1.0 - p_out_pool))

    out.append(f"\\newcommand{{\\CalibXorReads}}{{{xor_reads}}}")
    out.append(f"\\newcommand{{\\CalibPoolBytes}}{{{pool_bytes}}}")
    out.append(f"\\newcommand{{\\CalibOutputBits}}{{{output_bits}}}")
    out.append(f"\\newcommand{{\\CalibPWorst}}{{{p_worst:.4f}}}")
    out.append(f"\\newcommand{{\\CalibNeffByte}}{{{n_eff_byte}}}")
    out.append(f"\\newcommand{{\\CalibNeffPool}}{{{n_eff_pool}}}")
    out.append(f"\\newcommand{{\\CalibPOutByte}}{{{p_out_byte:.5f}}}")
    out.append(f"\\newcommand{{\\CalibPOutPool}}{{{p_out_pool:.5f}}}")
    out.append(f"\\newcommand{{\\CalibMinEntropyBit}}{{{h_inf_bit:.5f}}}")
    out.append(f"\\newcommand{{\\CalibMinEntropyOutput}}{{{h_inf_out:.5f}}}")
    out.append(f"\\newcommand{{\\CalibDisplayCount}}{{{len(pairs)}}}")
    out.append(f"\\newcommand{{\\CalibTotalCount}}{{{len(pairs_all)}}}")
    if len(pairs_all) > display_limit:
        out.append("\\newcommand{\\CalibTruncatedNote}{\\vspace{-0.2em}\\begin{center}\\scriptsize(First 9 traces shown in-section; full dataset in Appendix A.)\\end{center}}")
    else:
        out.append("\\newcommand{\\CalibTruncatedNote}{}")

    return "\n".join(out) + "\n"


def _f(x: str) -> float:
    try:
        return float(x.strip())
    except Exception:
        return 0.0


def build_appendix_b_model_summary(datasets_root: Path) -> str:
    appendix_b_dirs = [
        p for p in (datasets_root / "appendix_b", datasets_root / "appendex_b") if p.exists()
    ]
    model_dirs: List[Path] = []
    for appendix_b in appendix_b_dirs:
        model_dirs.extend([p for p in sorted(appendix_b.glob("model*")) if p.is_dir()])

    out: List[str] = []
    out.append("% auto-generated by scripts/generate_docs_data.py")

    if not model_dirs:
        out.append("No model directories were found in \\texttt{datasets/appendix\\_b} (or \\texttt{datasets/appendex\\_b}) at build time.")
        return "\n".join(out) + "\n"

    model_tables: List[str] = []
    for model_dir in model_dirs:
        csv_files = sorted(model_dir.glob("*.csv"))
        if not csv_files:
            continue

        per_unit: Dict[str, Dict[str, object]] = {}

        for csv_path in csv_files:
            with csv_path.open("r", encoding="utf-8", errors="replace", newline="") as f:
                reader = csv.DictReader(f)
                for r in reader:
                    unit = (r.get("primitive", "") or "").strip() or "UNKNOWN"
                    d = per_unit.setdefault(
                        unit,
                        {
                            "n": 0,
                            "pass6": 0,
                            "pass4": 0,
                            "sigma": [],
                            "d6": [],
                            "d4": [],
                            "med_w": [],
                            "med_r": [],
                            "med_e": [],
                            "ov6_w": [],
                            "ov6_r": [],
                            "ov6_e": [],
                            "ov4_w": [],
                            "ov4_r": [],
                            "ov4_e": [],
                        },
                    )
                    d["n"] = int(d["n"]) + 1
                    if (r.get("pass_c6", "").strip().upper() == "PASS"):
                        d["pass6"] = int(d["pass6"]) + 1
                    if (r.get("pass_c4", "").strip().upper() == "PASS"):
                        d["pass4"] = int(d["pass4"]) + 1

                    cast = lambda k: _f(r.get(k, "0"))
                    d["sigma"].append(cast("sigma"))
                    d["d6"].append(cast("max_delta_c6"))
                    d["d4"].append(cast("max_delta_c4"))
                    d["med_w"].append(cast("median_dev_worst"))
                    d["med_r"].append(cast("median_dev_random"))
                    d["med_e"].append(cast("median_dev_edge"))
                    d["ov6_w"].append(cast("over_worst_c6_pct"))
                    d["ov6_r"].append(cast("over_random_c6_pct"))
                    d["ov6_e"].append(cast("over_edge_c6_pct"))
                    d["ov4_w"].append(cast("over_worst_c4_pct"))
                    d["ov4_r"].append(cast("over_random_c4_pct"))
                    d["ov4_e"].append(cast("over_edge_c4_pct"))

        if not per_unit:
            continue

        model_name = model_dir.name.replace("model", "Rev ")
        total_rows = sum(int(v["n"]) for v in per_unit.values())
        unit_rows: List[str] = []

        for unit in sorted(per_unit.keys()):
            d = per_unit[unit]
            n = int(d["n"])
            if n <= 0:
                continue
            mean = lambda key: (statistics.mean(d[key]) if d[key] else 0.0)
            max_over_c6 = max(
                max(d["ov6_w"]) if d["ov6_w"] else 0.0,
                max(d["ov6_r"]) if d["ov6_r"] else 0.0,
                max(d["ov6_e"]) if d["ov6_e"] else 0.0,
            )
            unit_pass = max_over_c6 < 75.0
            row_color = "green!8" if unit_pass else "red!10"
            unit_color = "ForestGreen" if unit_pass else "BrickRed"
            unit_rows.append(
                f"\\rowcolor{{{row_color}}}\\textcolor{{{unit_color}}}{{{tex_escape(unit)}}} & "
                f"{mean('sigma'):.2f} & "
                f"{mean('d6'):.2f}/{mean('d4'):.2f} & "
                f"{mean('med_w'):.1f}/{mean('med_r'):.1f}/{mean('med_e'):.1f} & "
                f"{mean('ov6_w'):.2f}\\%/{mean('ov6_r'):.2f}\\%/{mean('ov6_e'):.2f}\\% & "
                f"{mean('ov4_w'):.2f}\\%/{mean('ov4_r'):.2f}\\%/{mean('ov4_e'):.2f}\\% \\\\"
            )

        model_tables.append("\\begin{table}[htbp]")
        model_tables.append("\\centering")
        model_tables.append(
            f"\\caption{{Timing summary by unit for {tex_escape(model_name)}.}}"
        )
        model_tables.append("\\renewcommand{\\arraystretch}{1.12}")
        model_tables.append("{\\footnotesize")
        model_tables.append("\\begin{tabular}{lccccc}")
        model_tables.append("\\hline")
        model_tables.append("\\textbf{Unit} & \\textbf{Avg $\\sigma$} & \\textbf{Avg $\\Delta$ (c6/c4)} & \\textbf{MedDev (W/R/E)} & \\textbf{Over\\% c6 (W/R/E)} & \\textbf{Over\\% c4 (W/R/E)} \\\\")
        model_tables.append("\\hline")
        model_tables.extend(unit_rows)
        model_tables.append("\\hline")
        model_tables.append("\\end{tabular}")
        model_tables.append("}")
        model_tables.append("\\vspace{-0.6em}")
        model_tables.append(f"{{\\scriptsize\\emph{{Source files parsed: {len(csv_files)}}}}}")
        model_tables.append("\\end{table}")
        model_tables.append("\\vspace{0.2em}")

    if not model_tables:
        out.append("No parseable timing CSV rows were found under \\texttt{datasets/appendix\\_b/model*} (or \\texttt{datasets/appendex\\_b/model*}).")
        return "\n".join(out) + "\n"

    out.extend(model_tables)
    return "\n".join(out) + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    DATASET_DIR.mkdir(parents=True, exist_ok=True)

    digest = manifest_hash([DATASET_DIR, APPENDIX_B_DIR, APPENDIX_B_ALT_DIR])
    old_digest = MANIFEST_FILE.read_text(encoding="utf-8").strip() if MANIFEST_FILE.exists() else ""

    if digest == old_digest and APPENDIX_TEX.exists() and CORR_TEX.exists() and APPENDIX_B_TEX.exists():
        print("docs-data: cache hit (datasets unchanged)")
        return 0

    appendix = build_appendix_include(DATASET_DIR)
    corr = build_correlation_macros(DATASET_DIR)
    appendix_b = build_appendix_b_model_summary(DATASETS_ROOT)

    changed = False
    changed |= write_if_changed(APPENDIX_TEX, appendix)
    changed |= write_if_changed(CORR_TEX, corr)
    changed |= write_if_changed(APPENDIX_B_TEX, appendix_b)

    MANIFEST_FILE.write_text(digest + "\n", encoding="utf-8")

    if changed:
        print("docs-data: regenerated generated/*.tex")
    else:
        print("docs-data: manifest updated (content unchanged)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
