# ----------------------------
# Makefile Options
# ----------------------------

NAME = P256TST
ICON = icon.png
DESCRIPTION = "P-256 Contest Test Suite"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
