PROJECT_ROOT := $(realpath $(CURDIR)/../..)
TLS_CORE := $(PROJECT_ROOT)/src/tls/core
TLS_INC := $(PROJECT_ROOT)/src/tls/includes
LWIP_INC := $(PROJECT_ROOT)/src/include
X25519_DIR := $(PROJECT_ROOT)/src/tls/contrib/x25519/src
