# ----------------------------
# Makefile Options
# ----------------------------
# Dyload variant: links against the resident lwip.lib.

NAME = XPBKDF2
ICON = icon.png
ARCHIVED = NO
BSSHEAP_LOW = 0xD072C6
DESCRIPTION = "tls_pbkdf2 test"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

SOURCES = src/main.c

# ----------------------------

include $(shell cedev-config --makefile)
