; Auto-generated by tools/functable.py.  Do not edit by hand —
; run `make functable` after adding/removing public API.
;
; Symbols are grouped by defining source file. libload resolves
; by name (not slot index), so reordering across regenerations is
; safe — apps must be relinked, but no silent ABI break.

.assume adl=1
.section .rodata
.globl _fn_exports_table
.equ app, 0

.extern _lwip_start
.extern _lwip_poll_network_events
.extern _lwip_conn_create
.extern _lwip_conn_destroy
.extern _lwip_conn_connect
.extern _lwip_conn_write
.extern _lwip_conn_recved
.extern _lwip_conn_shutdown
.extern _lwip_conn_close
.extern _lwip_conn_abort
.extern _lwip_conn_set_arg
.extern _lwip_conn_set_connected
.extern _lwip_conn_set_recv
.extern _lwip_conn_set_sent
.extern _lwip_conn_set_err
.extern _lwip_conn_set_poll
.extern _lwip_conn_set_closed
.extern _tls_aes_init
.extern _tls_aes_ccm_init
.extern _tls_aes_ccm_encrypt
.extern _tls_aes_ccm_decrypt
.extern _tls_aes_update_aad
.extern _tls_aes_encrypt
.extern _tls_aes_update_ciphertext
.extern _tls_aes_digest
.extern _tls_aes_decrypt
.extern _tls_aes_verify
.extern _tls_asn1_cursor_init
.extern _tls_asn1_next
.extern _tls_asn1_child_cursor
.extern _tls_asn1_tag_number
.extern _tls_asn1_tag_class
.extern _tls_asn1_tag_constructed
.extern _tls_base64_encode
.extern _tls_base64_decode
.extern _tls_bytes_compare
.extern _tls_secure_memzero
.extern _tls_sha256_init
.extern _tls_sha256_update
.extern _tls_sha256_digest
.extern _tls_hash_context_init
.extern _tls_hash_update
.extern _tls_hash_digest
.extern _tls_mgf1
.extern _tls_hkdf_extract
.extern _tls_hkdf_expand
.extern _tls_hkdf_expand_label
.extern _tls_derive_secret
.extern _tls_hmac_context_init
.extern _tls_hmac_update
.extern _tls_hmac_digest
.extern _tls_keyobject_import_private
.extern _tls_keyobject_import_public
.extern _tls_keyobject_import_certificate
.extern _tls_x509_has_required_ca_constraints
.extern _tls_keyobject_destroy
.extern _tls_pbkdf2
.extern _tls_pkcs8_strerror
.extern _tls_pkcs8_import
.extern _tls_pkcs8_import_private
.extern _tls_pkcs8_import_public
.extern _tls_pkcs8_object_import_private
.extern _tls_pkcs8_object_import_public
.extern _tls_pkcs8_object_destroy
.extern _tls_random_init_entropy
.extern _tls_random
.extern _tls_random_bytes
.extern _tls_rng_healthcheck
.extern _tls_request_random_bytes
.extern _tls_rng_is_busy
.extern _tls_rsa_encode_oaep
.extern _tls_rsa_decode_oaep
.extern _tls_rsa_encrypt
.extern _tls_rsa_decrypt_signature
.extern _tls_rsa_pss_verify
.extern _tls_truststore_init
.extern _tls_truststore_lookup
.extern _tls_x509_has_valid_constraints
.extern _tls_x509_parse_certificate
.extern _tls_x509_import_and_parse_certificate
.extern _tls_x509_import_certificate
.extern _tls_x509_object_destroy
.extern _acd_add
.extern _acd_remove
.extern _acd_start
.extern _acd_stop
.extern _acd_arp_reply
.extern _acd_network_changed_link_down
.extern _acd_netif_ip_addr_changed
.extern _altcp_new
.extern _altcp_new_ip6
.extern _altcp_new_ip_type
.extern _altcp_arg
.extern _altcp_accept
.extern _altcp_recv
.extern _altcp_sent
.extern _altcp_poll
.extern _altcp_err
.extern _altcp_recved
.extern _altcp_bind
.extern _altcp_connect
.extern _altcp_listen_with_backlog_and_err
.extern _altcp_abort
.extern _altcp_close
.extern _altcp_shutdown
.extern _altcp_write
.extern _altcp_output
.extern _altcp_mss
.extern _altcp_sndbuf
.extern _altcp_sndqueuelen
.extern _altcp_nagle_disable
.extern _altcp_nagle_enable
.extern _altcp_nagle_disabled
.extern _altcp_setprio
.extern _altcp_get_tcp_addrinfo
.extern _altcp_get_ip
.extern _altcp_get_port
.extern _altcp_dbg_get_tcp_state
.extern _altcp_tls_create_config_server
.extern _altcp_tls_config_server_add_privkey_cert
.extern _altcp_tls_create_config_server_privkey_cert
.extern _altcp_tls_create_config_client
.extern _altcp_tls_create_config_client_2wayauth
.extern _altcp_tls_configure_alpn_protocols
.extern _altcp_tls_free_config
.extern _altcp_tls_wrap
.extern _altcp_tls_new
.extern _altcp_tls_alloc
.extern _autoip_set_struct
.extern _autoip_remove_struct
.extern _autoip_start
.extern _autoip_stop
.extern _autoip_network_changed_link_up
.extern _autoip_network_changed_link_down
.extern _autoip_supplied_address
.extern _autoip_accept_packet
.extern _lwip_htons
.extern _lwip_htonl
.extern _lwip_itoa
.extern _lwip_strnicmp
.extern _lwip_stricmp
.extern _lwip_strnstr
.extern _lwip_strnistr
.extern _lwip_memcmp_consttime
.extern _dhcp_set_struct
.extern _dhcp_cleanup
.extern _dhcp_start
.extern _dhcp_renew
.extern _dhcp_release
.extern _dhcp_stop
.extern _dhcp_release_and_stop
.extern _dhcp_inform
.extern _dhcp_network_changed_link_up
.extern _dhcp_supplied_address
.extern _dns_setserver
.extern _dns_getserver
.extern _dns_gethostbyname
.extern _dns_gethostbyname_addrtype
.extern _etharp_find_addr
.extern _etharp_get_entry
.extern _etharp_output
.extern _etharp_query
.extern _etharp_request
.extern _etharp_cleanup_netif
.extern _etharp_acd_probe
.extern _etharp_acd_announce
.extern _etharp_input
.extern _icmp_input
.extern _icmp_dest_unreach
.extern _icmp_time_exceeded
.extern _icmp6_input
.extern _icmp6_dest_unreach
.extern _icmp6_packet_too_big
.extern _icmp6_time_exceeded
.extern _icmp6_time_exceeded_with_addrs
.extern _icmp6_param_problem
.extern _igmp_start
.extern _igmp_stop
.extern _igmp_report_groups
.extern _igmp_lookfor_group
.extern _igmp_input
.extern _igmp_joingroup
.extern _igmp_joingroup_netif
.extern _igmp_leavegroup
.extern _igmp_leavegroup_netif
.extern _inet_chksum
.extern _inet_chksum_pbuf
.extern _inet_chksum_pseudo
.extern _inet_chksum_pseudo_partial
.extern _ip6_chksum_pseudo
.extern _ip6_chksum_pseudo_partial
.extern _ip_chksum_pseudo
.extern _ip_chksum_pseudo_partial
.extern _lwip_init
.extern _ip_input
.extern _ip4_route
.extern _ip4_input
.extern _ip4_output
.extern _ip4_output_if
.extern _ip4_output_if_src
.extern _ip4_output_if_opt
.extern _ip4_output_if_opt_src
.extern _ip4_set_default_multicast_netif
.extern _ip4_addr_isbroadcast_u32
.extern _ip4_addr_netmask_valid
.extern _ipaddr_addr
.extern _ip4addr_aton
.extern _ip4addr_ntoa
.extern _ip4addr_ntoa_r
.extern _ip4_reass
.extern _ip4_frag
.extern _ip6_route
.extern _ip6_select_source_address
.extern _ip6_input
.extern _ip6_output
.extern _ip6_output_if
.extern _ip6_output_if_src
.extern _ip6_options_add_hbh_ra
.extern _ip6addr_aton
.extern _ip6addr_ntoa
.extern _ip6addr_ntoa_r
.extern _ip6_reass
.extern _ip6_frag
.extern _ipaddr_ntoa
.extern _ipaddr_ntoa_r
.extern _ipaddr_aton
.extern _mem_trim
.extern _mem_malloc
.extern _mem_calloc
.extern _mem_free
.extern _memp_malloc
.extern _memp_free
.extern _mld6_stop
.extern _mld6_report_groups
.extern _mld6_lookfor_group
.extern _mld6_input
.extern _mld6_joingroup
.extern _mld6_joingroup_netif
.extern _mld6_leavegroup
.extern _mld6_leavegroup_netif
.extern _nd6_input
.extern _nd6_clear_destination_cache
.extern _nd6_find_route
.extern _nd6_get_next_hop_addr_or_queue
.extern _nd6_get_destination_mtu
.extern _nd6_reachability_hint
.extern _nd6_cleanup_netif
.extern _nd6_adjust_mld_membership
.extern _nd6_restart_netif
.extern _netif_alloc_client_data_id
.extern _netif_add_noaddr
.extern _netif_add
.extern _netif_set_addr
.extern _netif_remove
.extern _netif_find
.extern _netif_set_default
.extern _netif_set_ipaddr
.extern _netif_set_netmask
.extern _netif_set_gw
.extern _netif_set_up
.extern _netif_set_down
.extern _netif_set_status_callback
.extern _netif_set_remove_callback
.extern _netif_set_link_up
.extern _netif_set_link_down
.extern _netif_set_link_callback
.extern _netif_loop_output
.extern _netif_poll
.extern _netif_poll_all
.extern _netif_input
.extern _netif_ip6_addr_set
.extern _netif_ip6_addr_set_parts
.extern _netif_ip6_addr_set_state
.extern _netif_get_ip6_addr_match
.extern _netif_create_ip6_linklocal_address
.extern _netif_add_ip6_address
.extern _netif_name_to_index
.extern _netif_index_to_name
.extern _netif_get_by_index
.extern _netif_add_ext_callback
.extern _netif_remove_ext_callback
.extern _pbuf_free_ooseq
.extern _pbuf_alloc
.extern _pbuf_alloc_reference
.extern _pbuf_alloced_custom
.extern _pbuf_realloc
.extern _pbuf_header
.extern _pbuf_header_force
.extern _pbuf_add_header
.extern _pbuf_add_header_force
.extern _pbuf_remove_header
.extern _pbuf_free_header
.extern _pbuf_ref
.extern _pbuf_free
.extern _pbuf_clen
.extern _pbuf_cat
.extern _pbuf_chain
.extern _pbuf_dechain
.extern _pbuf_copy
.extern _pbuf_copy_partial_pbuf
.extern _pbuf_copy_partial
.extern _pbuf_get_contiguous
.extern _pbuf_take
.extern _pbuf_take_at
.extern _pbuf_skip
.extern _pbuf_coalesce
.extern _pbuf_clone
.extern _pbuf_get_at
.extern _pbuf_try_get_at
.extern _pbuf_put_at
.extern _pbuf_memcmp
.extern _pbuf_memfind
.extern _pbuf_strstr
.extern _raw_new
.extern _raw_new_ip_type
.extern _raw_remove
.extern _raw_bind
.extern _raw_bind_netif
.extern _raw_connect
.extern _raw_disconnect
.extern _raw_sendto
.extern _raw_sendto_if_src
.extern _raw_send
.extern _raw_recv
.extern _lwip_sntp_set_timezone_offset
.extern _lwip_sntp_set_dst_enabled
.extern _lwip_sntp_set_time
.extern _lwip_sntp_reset_flag
.extern _lwip_sntp_time_was_set
.extern _lwip_sntp_get_unix_time
.extern _sys_timeout
.extern _sys_untimeout
.extern _tcp_new
.extern _tcp_new_ip_type
.extern _tcp_arg
.extern _tcp_recv
.extern _tcp_sent
.extern _tcp_err
.extern _tcp_accept
.extern _tcp_poll
.extern _tcp_backlog_delayed
.extern _tcp_backlog_accepted
.extern _tcp_recved
.extern _tcp_bind
.extern _tcp_bind_netif
.extern _tcp_connect
.extern _tcp_listen_with_backlog_and_err
.extern _tcp_listen_with_backlog
.extern _tcp_abort
.extern _tcp_close
.extern _tcp_shutdown
.extern _tcp_write
.extern _tcp_setprio
.extern _tcp_output
.extern _tcp_tcp_get_tcp_addrinfo
.extern _udp_new
.extern _udp_new_ip_type
.extern _udp_remove
.extern _udp_bind
.extern _udp_bind_netif
.extern _udp_connect
.extern _udp_disconnect
.extern _udp_recv
.extern _udp_sendto_if
.extern _udp_sendto_if_src
.extern _udp_sendto
.extern _udp_send
.extern _udp_input
.extern _udp_netif_ip_addr_changed
.extern _ethernet_input
.extern _ethernet_output
.extern _eth_set_rx_throttle
.extern _eth_set_rx_drain_interval_ms
.extern _eth_get_interfaces
.extern _eth_usb_event_callback

_fn_exports_table:

; --- src/lwIP.c ---
    d24 _lwip_start - app
    d24 _lwip_poll_network_events - app
    d24 _lwip_conn_create - app
    d24 _lwip_conn_destroy - app
    d24 _lwip_conn_connect - app
    d24 _lwip_conn_write - app
    d24 _lwip_conn_recved - app
    d24 _lwip_conn_shutdown - app
    d24 _lwip_conn_close - app
    d24 _lwip_conn_abort - app
    d24 _lwip_conn_set_arg - app
    d24 _lwip_conn_set_connected - app
    d24 _lwip_conn_set_recv - app
    d24 _lwip_conn_set_sent - app
    d24 _lwip_conn_set_err - app
    d24 _lwip_conn_set_poll - app
    d24 _lwip_conn_set_closed - app

; --- src/tls/core/aes.c ---
    d24 _tls_aes_init - app
    d24 _tls_aes_ccm_init - app
    d24 _tls_aes_ccm_encrypt - app
    d24 _tls_aes_ccm_decrypt - app
    d24 _tls_aes_update_aad - app
    d24 _tls_aes_encrypt - app
    d24 _tls_aes_update_ciphertext - app
    d24 _tls_aes_digest - app
    d24 _tls_aes_decrypt - app
    d24 _tls_aes_verify - app

; --- src/tls/core/asn1.c ---
    d24 _tls_asn1_cursor_init - app
    d24 _tls_asn1_next - app
    d24 _tls_asn1_child_cursor - app
    d24 _tls_asn1_tag_number - app
    d24 _tls_asn1_tag_class - app
    d24 _tls_asn1_tag_constructed - app

; --- src/tls/core/base64.c ---
    d24 _tls_base64_encode - app
    d24 _tls_base64_decode - app

; --- src/tls/core/bytes.s ---
    d24 _tls_bytes_compare - app

; --- src/tls/core/bytes.c ---
    d24 _tls_secure_memzero - app

; --- src/tls/core/sha256.s ---
    d24 _tls_sha256_init - app
    d24 _tls_sha256_update - app
    d24 _tls_sha256_digest - app

; --- src/tls/core/hash.c ---
    d24 _tls_hash_context_init - app
    d24 _tls_hash_update - app
    d24 _tls_hash_digest - app
    d24 _tls_mgf1 - app

; --- src/tls/core/hkdf.c ---
    d24 _tls_hkdf_extract - app
    d24 _tls_hkdf_expand - app
    d24 _tls_hkdf_expand_label - app
    d24 _tls_derive_secret - app

; --- src/tls/core/hmac.c ---
    d24 _tls_hmac_context_init - app
    d24 _tls_hmac_update - app
    d24 _tls_hmac_digest - app

; --- src/tls/core/keyobject.c ---
    d24 _tls_keyobject_import_private - app
    d24 _tls_keyobject_import_public - app
    d24 _tls_keyobject_import_certificate - app

; --- src/tls/core/x509.c ---
    d24 _tls_x509_has_required_ca_constraints - app

; --- src/tls/core/keyobject.c ---
    d24 _tls_keyobject_destroy - app

; --- src/tls/core/passwords.c ---
    d24 _tls_pbkdf2 - app

; --- src/tls/core/pkcs8.c ---
    d24 _tls_pkcs8_strerror - app
    d24 _tls_pkcs8_import - app
    d24 _tls_pkcs8_import_private - app
    d24 _tls_pkcs8_import_public - app
    d24 _tls_pkcs8_object_import_private - app
    d24 _tls_pkcs8_object_import_public - app
    d24 _tls_pkcs8_object_destroy - app

; --- src/tls/core/random.s ---
    d24 _tls_random_init_entropy - app
    d24 _tls_random - app
    d24 _tls_random_bytes - app

; --- src/tls/core/random.c ---
    d24 _tls_rng_healthcheck - app
    d24 _tls_request_random_bytes - app
    d24 _tls_rng_is_busy - app

; --- src/tls/core/rsa.c ---
    d24 _tls_rsa_encode_oaep - app
    d24 _tls_rsa_decode_oaep - app
    d24 _tls_rsa_encrypt - app
    d24 _tls_rsa_decrypt_signature - app
    d24 _tls_rsa_pss_verify - app

; --- src/tls/core/truststore.c ---
    d24 _tls_truststore_init - app
    d24 _tls_truststore_lookup - app

; --- src/tls/core/x509.c ---
    d24 _tls_x509_has_valid_constraints - app
    d24 _tls_x509_parse_certificate - app
    d24 _tls_x509_import_and_parse_certificate - app
    d24 _tls_x509_import_certificate - app
    d24 _tls_x509_object_destroy - app

; --- src/core/ipv4/acd.c ---
    d24 _acd_add - app
    d24 _acd_remove - app
    d24 _acd_start - app
    d24 _acd_stop - app
    d24 _acd_arp_reply - app
    d24 _acd_network_changed_link_down - app
    d24 _acd_netif_ip_addr_changed - app

; --- src/core/altcp.c ---
    d24 _altcp_new - app
    d24 _altcp_new_ip6 - app
    d24 _altcp_new_ip_type - app
    d24 _altcp_arg - app
    d24 _altcp_accept - app
    d24 _altcp_recv - app
    d24 _altcp_sent - app
    d24 _altcp_poll - app
    d24 _altcp_err - app
    d24 _altcp_recved - app
    d24 _altcp_bind - app
    d24 _altcp_connect - app
    d24 _altcp_listen_with_backlog_and_err - app
    d24 _altcp_abort - app
    d24 _altcp_close - app
    d24 _altcp_shutdown - app
    d24 _altcp_write - app
    d24 _altcp_output - app
    d24 _altcp_mss - app
    d24 _altcp_sndbuf - app
    d24 _altcp_sndqueuelen - app
    d24 _altcp_nagle_disable - app
    d24 _altcp_nagle_enable - app
    d24 _altcp_nagle_disabled - app
    d24 _altcp_setprio - app
    d24 _altcp_get_tcp_addrinfo - app
    d24 _altcp_get_ip - app
    d24 _altcp_get_port - app
    d24 _altcp_dbg_get_tcp_state - app

; --- src/apps/altcp_tls/altcp_tls_ce.c ---
    d24 _altcp_tls_create_config_server - app
    d24 _altcp_tls_config_server_add_privkey_cert - app
    d24 _altcp_tls_create_config_server_privkey_cert - app
    d24 _altcp_tls_create_config_client - app
    d24 _altcp_tls_create_config_client_2wayauth - app
    d24 _altcp_tls_configure_alpn_protocols - app
    d24 _altcp_tls_free_config - app
    d24 _altcp_tls_wrap - app

; --- src/core/altcp_alloc.c ---
    d24 _altcp_tls_new - app
    d24 _altcp_tls_alloc - app

; --- src/core/ipv4/autoip.c ---
    d24 _autoip_set_struct - app
    d24 _autoip_remove_struct - app
    d24 _autoip_start - app
    d24 _autoip_stop - app
    d24 _autoip_network_changed_link_up - app
    d24 _autoip_network_changed_link_down - app
    d24 _autoip_supplied_address - app
    d24 _autoip_accept_packet - app

; --- src/core/def.c ---
    d24 _lwip_htons - app
    d24 _lwip_htonl - app
    d24 _lwip_itoa - app
    d24 _lwip_strnicmp - app
    d24 _lwip_stricmp - app
    d24 _lwip_strnstr - app
    d24 _lwip_strnistr - app
    d24 _lwip_memcmp_consttime - app

; --- src/core/ipv4/dhcp.c ---
    d24 _dhcp_set_struct - app
    d24 _dhcp_cleanup - app
    d24 _dhcp_start - app
    d24 _dhcp_renew - app
    d24 _dhcp_release - app
    d24 _dhcp_stop - app
    d24 _dhcp_release_and_stop - app
    d24 _dhcp_inform - app
    d24 _dhcp_network_changed_link_up - app
    d24 _dhcp_supplied_address - app

; --- src/core/dns.c ---
    d24 _dns_setserver - app
    d24 _dns_getserver - app
    d24 _dns_gethostbyname - app
    d24 _dns_gethostbyname_addrtype - app

; --- src/core/ipv4/etharp.c ---
    d24 _etharp_find_addr - app
    d24 _etharp_get_entry - app
    d24 _etharp_output - app
    d24 _etharp_query - app
    d24 _etharp_request - app
    d24 _etharp_cleanup_netif - app
    d24 _etharp_acd_probe - app
    d24 _etharp_acd_announce - app
    d24 _etharp_input - app

; --- src/core/ipv4/icmp.c ---
    d24 _icmp_input - app
    d24 _icmp_dest_unreach - app
    d24 _icmp_time_exceeded - app

; --- src/core/ipv6/icmp6.c ---
    d24 _icmp6_input - app
    d24 _icmp6_dest_unreach - app
    d24 _icmp6_packet_too_big - app
    d24 _icmp6_time_exceeded - app
    d24 _icmp6_time_exceeded_with_addrs - app
    d24 _icmp6_param_problem - app

; --- src/core/ipv4/igmp.c ---
    d24 _igmp_start - app
    d24 _igmp_stop - app
    d24 _igmp_report_groups - app
    d24 _igmp_lookfor_group - app
    d24 _igmp_input - app
    d24 _igmp_joingroup - app
    d24 _igmp_joingroup_netif - app
    d24 _igmp_leavegroup - app
    d24 _igmp_leavegroup_netif - app

; --- src/core/inet_chksum.c ---
    d24 _inet_chksum - app
    d24 _inet_chksum_pbuf - app
    d24 _inet_chksum_pseudo - app
    d24 _inet_chksum_pseudo_partial - app
    d24 _ip6_chksum_pseudo - app
    d24 _ip6_chksum_pseudo_partial - app
    d24 _ip_chksum_pseudo - app
    d24 _ip_chksum_pseudo_partial - app

; --- src/core/init.c ---
    d24 _lwip_init - app

; --- src/core/ip.c ---
    d24 _ip_input - app

; --- src/core/ipv4/ip4.c ---
    d24 _ip4_route - app
    d24 _ip4_input - app
    d24 _ip4_output - app
    d24 _ip4_output_if - app
    d24 _ip4_output_if_src - app
    d24 _ip4_output_if_opt - app
    d24 _ip4_output_if_opt_src - app
    d24 _ip4_set_default_multicast_netif - app

; --- src/core/ipv4/ip4_addr.c ---
    d24 _ip4_addr_isbroadcast_u32 - app
    d24 _ip4_addr_netmask_valid - app
    d24 _ipaddr_addr - app
    d24 _ip4addr_aton - app
    d24 _ip4addr_ntoa - app
    d24 _ip4addr_ntoa_r - app

; --- src/core/ipv4/ip4_frag.c ---
    d24 _ip4_reass - app
    d24 _ip4_frag - app

; --- src/core/ipv6/ip6.c ---
    d24 _ip6_route - app
    d24 _ip6_select_source_address - app
    d24 _ip6_input - app
    d24 _ip6_output - app
    d24 _ip6_output_if - app
    d24 _ip6_output_if_src - app
    d24 _ip6_options_add_hbh_ra - app

; --- src/core/ipv6/ip6_addr.c ---
    d24 _ip6addr_aton - app
    d24 _ip6addr_ntoa - app
    d24 _ip6addr_ntoa_r - app

; --- src/core/ipv6/ip6_frag.c ---
    d24 _ip6_reass - app
    d24 _ip6_frag - app

; --- src/core/ip.c ---
    d24 _ipaddr_ntoa - app
    d24 _ipaddr_ntoa_r - app
    d24 _ipaddr_aton - app

; --- src/core/mem.c ---
    d24 _mem_trim - app
    d24 _mem_malloc - app
    d24 _mem_calloc - app
    d24 _mem_free - app

; --- src/core/memp.c ---
    d24 _memp_malloc - app
    d24 _memp_free - app

; --- src/core/ipv6/mld6.c ---
    d24 _mld6_stop - app
    d24 _mld6_report_groups - app
    d24 _mld6_lookfor_group - app
    d24 _mld6_input - app
    d24 _mld6_joingroup - app
    d24 _mld6_joingroup_netif - app
    d24 _mld6_leavegroup - app
    d24 _mld6_leavegroup_netif - app

; --- src/core/ipv6/nd6.c ---
    d24 _nd6_input - app
    d24 _nd6_clear_destination_cache - app
    d24 _nd6_find_route - app
    d24 _nd6_get_next_hop_addr_or_queue - app
    d24 _nd6_get_destination_mtu - app
    d24 _nd6_reachability_hint - app
    d24 _nd6_cleanup_netif - app
    d24 _nd6_adjust_mld_membership - app
    d24 _nd6_restart_netif - app

; --- src/core/netif.c ---
    d24 _netif_alloc_client_data_id - app
    d24 _netif_add_noaddr - app
    d24 _netif_add - app
    d24 _netif_set_addr - app
    d24 _netif_remove - app
    d24 _netif_find - app
    d24 _netif_set_default - app
    d24 _netif_set_ipaddr - app
    d24 _netif_set_netmask - app
    d24 _netif_set_gw - app
    d24 _netif_set_up - app
    d24 _netif_set_down - app
    d24 _netif_set_status_callback - app
    d24 _netif_set_remove_callback - app
    d24 _netif_set_link_up - app
    d24 _netif_set_link_down - app
    d24 _netif_set_link_callback - app
    d24 _netif_loop_output - app
    d24 _netif_poll - app
    d24 _netif_poll_all - app
    d24 _netif_input - app
    d24 _netif_ip6_addr_set - app
    d24 _netif_ip6_addr_set_parts - app
    d24 _netif_ip6_addr_set_state - app
    d24 _netif_get_ip6_addr_match - app
    d24 _netif_create_ip6_linklocal_address - app
    d24 _netif_add_ip6_address - app
    d24 _netif_name_to_index - app
    d24 _netif_index_to_name - app
    d24 _netif_get_by_index - app
    d24 _netif_add_ext_callback - app
    d24 _netif_remove_ext_callback - app

; --- src/core/pbuf.c ---
    d24 _pbuf_free_ooseq - app
    d24 _pbuf_alloc - app
    d24 _pbuf_alloc_reference - app
    d24 _pbuf_alloced_custom - app
    d24 _pbuf_realloc - app
    d24 _pbuf_header - app
    d24 _pbuf_header_force - app
    d24 _pbuf_add_header - app
    d24 _pbuf_add_header_force - app
    d24 _pbuf_remove_header - app
    d24 _pbuf_free_header - app
    d24 _pbuf_ref - app
    d24 _pbuf_free - app
    d24 _pbuf_clen - app
    d24 _pbuf_cat - app
    d24 _pbuf_chain - app
    d24 _pbuf_dechain - app
    d24 _pbuf_copy - app
    d24 _pbuf_copy_partial_pbuf - app
    d24 _pbuf_copy_partial - app
    d24 _pbuf_get_contiguous - app
    d24 _pbuf_take - app
    d24 _pbuf_take_at - app
    d24 _pbuf_skip - app
    d24 _pbuf_coalesce - app
    d24 _pbuf_clone - app
    d24 _pbuf_get_at - app
    d24 _pbuf_try_get_at - app
    d24 _pbuf_put_at - app
    d24 _pbuf_memcmp - app
    d24 _pbuf_memfind - app
    d24 _pbuf_strstr - app

; --- src/core/raw.c ---
    d24 _raw_new - app
    d24 _raw_new_ip_type - app
    d24 _raw_remove - app
    d24 _raw_bind - app
    d24 _raw_bind_netif - app
    d24 _raw_connect - app
    d24 _raw_disconnect - app
    d24 _raw_sendto - app
    d24 _raw_sendto_if_src - app
    d24 _raw_send - app
    d24 _raw_recv - app

; --- src/core/sntp_time.c ---
    d24 _lwip_sntp_set_timezone_offset - app
    d24 _lwip_sntp_set_dst_enabled - app
    d24 _lwip_sntp_set_time - app
    d24 _lwip_sntp_reset_flag - app
    d24 _lwip_sntp_time_was_set - app
    d24 _lwip_sntp_get_unix_time - app

; --- src/core/timeouts.c ---
    d24 _sys_timeout - app
    d24 _sys_untimeout - app

; --- src/core/tcp.c ---
    d24 _tcp_new - app
    d24 _tcp_new_ip_type - app
    d24 _tcp_arg - app
    d24 _tcp_recv - app
    d24 _tcp_sent - app
    d24 _tcp_err - app
    d24 _tcp_accept - app
    d24 _tcp_poll - app
    d24 _tcp_backlog_delayed - app
    d24 _tcp_backlog_accepted - app
    d24 _tcp_recved - app
    d24 _tcp_bind - app
    d24 _tcp_bind_netif - app
    d24 _tcp_connect - app
    d24 _tcp_listen_with_backlog_and_err - app
    d24 _tcp_listen_with_backlog - app
    d24 _tcp_abort - app
    d24 _tcp_close - app
    d24 _tcp_shutdown - app

; --- src/core/tcp_out.c ---
    d24 _tcp_write - app

; --- src/core/tcp.c ---
    d24 _tcp_setprio - app

; --- src/core/tcp_out.c ---
    d24 _tcp_output - app

; --- src/core/tcp.c ---
    d24 _tcp_tcp_get_tcp_addrinfo - app

; --- src/core/udp.c ---
    d24 _udp_new - app
    d24 _udp_new_ip_type - app
    d24 _udp_remove - app
    d24 _udp_bind - app
    d24 _udp_bind_netif - app
    d24 _udp_connect - app
    d24 _udp_disconnect - app
    d24 _udp_recv - app
    d24 _udp_sendto_if - app
    d24 _udp_sendto_if_src - app
    d24 _udp_sendto - app
    d24 _udp_send - app
    d24 _udp_input - app
    d24 _udp_netif_ip_addr_changed - app

; --- src/netif/ethernet.c ---
    d24 _ethernet_input - app
    d24 _ethernet_output - app

; --- src/drivers/usb_ethernet.c ---
    d24 _eth_set_rx_throttle - app
    d24 _eth_set_rx_drain_interval_ms - app
    d24 _eth_get_interfaces - app
    d24 _eth_usb_event_callback - app
