; Auto-generated by tools/functable.py.  Do not edit by hand —
; run `make functable` after adding/removing public API.
;
; Symbols are grouped by defining source file. libload resolves
; by name (not slot index), so reordering across regenerations is
; safe — apps must be relinked, but no silent ABI break.
;
; Layout:
;   db  'L','W','I','P','T','B'   6-byte magic (ascending memory order)
;   d24 <entry count>
;   d24 <offset>  ... one per exported symbol
;
; The libload bootstrap is emitted with the build-resolved address of
; _fn_exports_table; at load it checks the 6 magic bytes there and
; errors out on mismatch (stale/mismatched app paired with the lib).
;
; Each entry is the symbol's offset from the first byte of the app
; image (__app_base). Applications link at LOAD_ADDR = 0x000000, so a
; symbol's link-time address already IS its offset from the app base;
; we emit the bare symbol and the linker's relocation resolves it to
; that offset. A runtime reader recovers the real address as
; (relocated app base + offset).
;
; NB: we cannot write `symbol - __app_base` here — the assembler can't
; reduce a difference of two link-time-external symbols. With base 0
; the subtraction is a no-op anyway, so the bare symbol is correct.

.assume adl=1
.section .rodata
.globl _fn_exports_table

.extern _lwip_start
.extern _lwip_init_runtime_internal
.extern _lwip_poll_network_events
.extern _lwip_conn_create
.extern _lwip_conn_destroy
.extern _lwip_conn_connect
.extern _lwip_conn_write
.extern _lwip_conn_recved
.extern _lwip_conn_shutdown
.extern _lwip_conn_close
.extern _lwip_conn_abort
.extern _lwip_conn_set_arg
.extern _lwip_conn_set_connected
.extern _lwip_conn_set_recv
.extern _lwip_conn_set_sent
.extern _lwip_conn_set_err
.extern _lwip_conn_set_poll
.extern _lwip_conn_set_closed
.extern _tls_aes_init
.extern _tls_aes_ccm_init
.extern _tls_aes_ccm_encrypt
.extern _tls_aes_ccm_decrypt
.extern _tls_aes_update_aad
.extern _tls_aes_encrypt
.extern _tls_aes_update_ciphertext
.extern _tls_aes_digest
.extern _tls_aes_decrypt
.extern _tls_aes_verify
.extern _tls_asn1_cursor_init
.extern _tls_asn1_next
.extern _tls_asn1_child_cursor
.extern _tls_asn1_tag_number
.extern _tls_asn1_tag_class
.extern _tls_asn1_tag_constructed
.extern _tls_base64_encode
.extern _tls_base64_decode
.extern _tls_bytes_compare
.extern _tls_secure_memzero
.extern _tls_sha256_init
.extern _tls_sha256_update
.extern _tls_sha256_digest
.extern _tls_hash_context_init
.extern _tls_hash_update
.extern _tls_hash_digest
.extern _tls_mgf1
.extern _tls_hkdf_extract
.extern _tls_hkdf_expand
.extern _tls_hkdf_expand_label
.extern _tls_derive_secret
.extern _tls_hmac_context_init
.extern _tls_hmac_update
.extern _tls_hmac_digest
.extern _tls_keyobject_import_private
.extern _tls_keyobject_import_public
.extern _tls_keyobject_import_certificate
.extern _tls_x509_has_required_ca_constraints
.extern _tls_keyobject_destroy
.extern _tls_pbkdf2
.extern _tls_pkcs8_strerror
.extern _tls_pkcs8_import
.extern _tls_pkcs8_import_private
.extern _tls_pkcs8_import_public
.extern _tls_pkcs8_object_import_private
.extern _tls_pkcs8_object_import_public
.extern _tls_pkcs8_object_destroy
.extern _tls_random_init_entropy
.extern _tls_random
.extern _tls_random_bytes
.extern _tls_rng_healthcheck
.extern _tls_request_random_bytes
.extern _tls_rng_is_busy
.extern _tls_rsa_encode_oaep
.extern _tls_rsa_decode_oaep
.extern _tls_rsa_encrypt
.extern _tls_rsa_decrypt_signature
.extern _tls_rsa_pss_verify
.extern _tls_truststore_init
.extern _tls_truststore_lookup
.extern _tls_x509_has_valid_constraints
.extern _tls_x509_parse_certificate
.extern _tls_x509_import_and_parse_certificate
.extern _tls_x509_import_certificate
.extern _tls_x509_object_destroy
.extern _acd_add
.extern _acd_remove
.extern _acd_start
.extern _acd_stop
.extern _acd_arp_reply
.extern _acd_network_changed_link_down
.extern _acd_netif_ip_addr_changed
.extern _altcp_new
.extern _altcp_new_ip6
.extern _altcp_new_ip_type
.extern _altcp_arg
.extern _altcp_accept
.extern _altcp_recv
.extern _altcp_sent
.extern _altcp_poll
.extern _altcp_err
.extern _altcp_recved
.extern _altcp_bind
.extern _altcp_connect
.extern _altcp_listen_with_backlog_and_err
.extern _altcp_abort
.extern _altcp_close
.extern _altcp_shutdown
.extern _altcp_write
.extern _altcp_output
.extern _altcp_mss
.extern _altcp_sndbuf
.extern _altcp_sndqueuelen
.extern _altcp_nagle_disable
.extern _altcp_nagle_enable
.extern _altcp_nagle_disabled
.extern _altcp_setprio
.extern _altcp_get_tcp_addrinfo
.extern _altcp_get_ip
.extern _altcp_get_port
.extern _altcp_tls_create_config_server
.extern _altcp_tls_config_server_add_privkey_cert
.extern _altcp_tls_create_config_server_privkey_cert
.extern _altcp_tls_create_config_client
.extern _altcp_tls_create_config_client_2wayauth
.extern _altcp_tls_configure_alpn_protocols
.extern _altcp_tls_free_config
.extern _altcp_tls_wrap
.extern _altcp_tls_new
.extern _altcp_tls_alloc
.extern _autoip_set_struct
.extern _autoip_remove_struct
.extern _autoip_start
.extern _autoip_stop
.extern _autoip_network_changed_link_up
.extern _autoip_network_changed_link_down
.extern _autoip_supplied_address
.extern _autoip_accept_packet
.extern _lwip_htons
.extern _lwip_htonl
.extern _lwip_itoa
.extern _lwip_strnicmp
.extern _lwip_stricmp
.extern _lwip_strnstr
.extern _lwip_strnistr
.extern _lwip_memcmp_consttime
.extern _dhcp_set_struct
.extern _dhcp_cleanup
.extern _dhcp_start
.extern _dhcp_renew
.extern _dhcp_release
.extern _dhcp_stop
.extern _dhcp_release_and_stop
.extern _dhcp_inform
.extern _dhcp_network_changed_link_up
.extern _dhcp_supplied_address
.extern _dns_setserver
.extern _dns_getserver
.extern _dns_gethostbyname
.extern _dns_gethostbyname_addrtype
.extern _etharp_find_addr
.extern _etharp_get_entry
.extern _etharp_output
.extern _etharp_query
.extern _etharp_request
.extern _etharp_cleanup_netif
.extern _etharp_acd_probe
.extern _etharp_acd_announce
.extern _etharp_input
.extern _icmp_input
.extern _icmp_dest_unreach
.extern _icmp_time_exceeded
.extern _icmp6_input
.extern _icmp6_dest_unreach
.extern _icmp6_packet_too_big
.extern _icmp6_time_exceeded
.extern _icmp6_time_exceeded_with_addrs
.extern _icmp6_param_problem
.extern _igmp_start
.extern _igmp_stop
.extern _igmp_report_groups
.extern _igmp_lookfor_group
.extern _igmp_input
.extern _igmp_joingroup
.extern _igmp_joingroup_netif
.extern _igmp_leavegroup
.extern _igmp_leavegroup_netif
.extern _inet_chksum
.extern _inet_chksum_pbuf
.extern _inet_chksum_pseudo
.extern _inet_chksum_pseudo_partial
.extern _ip6_chksum_pseudo
.extern _ip6_chksum_pseudo_partial
.extern _ip_chksum_pseudo
.extern _ip_chksum_pseudo_partial
.extern _lwip_init
.extern _ip_input
.extern _ip4_route
.extern _ip4_input
.extern _ip4_output
.extern _ip4_output_if
.extern _ip4_output_if_src
.extern _ip4_output_if_opt
.extern _ip4_output_if_opt_src
.extern _ip4_set_default_multicast_netif
.extern _ip4_addr_isbroadcast_u32
.extern _ip4_addr_netmask_valid
.extern _ipaddr_addr
.extern _ip4addr_aton
.extern _ip4addr_ntoa
.extern _ip4addr_ntoa_r
.extern _ip4_reass
.extern _ip4_frag
.extern _ip6_route
.extern _ip6_select_source_address
.extern _ip6_input
.extern _ip6_output
.extern _ip6_output_if
.extern _ip6_output_if_src
.extern _ip6_options_add_hbh_ra
.extern _ip6addr_aton
.extern _ip6addr_ntoa
.extern _ip6addr_ntoa_r
.extern _ip6_reass
.extern _ip6_frag
.extern _ipaddr_ntoa
.extern _ipaddr_ntoa_r
.extern _ipaddr_aton
.extern _mem_trim
.extern _mem_malloc
.extern _mem_calloc
.extern _mem_free
.extern _memp_malloc
.extern _memp_free
.extern _mld6_stop
.extern _mld6_report_groups
.extern _mld6_lookfor_group
.extern _mld6_input
.extern _mld6_joingroup
.extern _mld6_joingroup_netif
.extern _mld6_leavegroup
.extern _mld6_leavegroup_netif
.extern _nd6_input
.extern _nd6_clear_destination_cache
.extern _nd6_find_route
.extern _nd6_get_next_hop_addr_or_queue
.extern _nd6_get_destination_mtu
.extern _nd6_reachability_hint
.extern _nd6_cleanup_netif
.extern _nd6_adjust_mld_membership
.extern _nd6_restart_netif
.extern _netif_alloc_client_data_id
.extern _netif_add_noaddr
.extern _netif_add
.extern _netif_set_addr
.extern _netif_remove
.extern _netif_find
.extern _netif_set_default
.extern _netif_set_ipaddr
.extern _netif_set_netmask
.extern _netif_set_gw
.extern _netif_set_up
.extern _netif_set_down
.extern _netif_set_status_callback
.extern _netif_set_remove_callback
.extern _netif_set_link_up
.extern _netif_set_link_down
.extern _netif_set_link_callback
.extern _netif_loop_output
.extern _netif_poll
.extern _netif_poll_all
.extern _netif_input
.extern _netif_ip6_addr_set
.extern _netif_ip6_addr_set_parts
.extern _netif_ip6_addr_set_state
.extern _netif_get_ip6_addr_match
.extern _netif_create_ip6_linklocal_address
.extern _netif_add_ip6_address
.extern _netif_name_to_index
.extern _netif_index_to_name
.extern _netif_get_by_index
.extern _netif_add_ext_callback
.extern _netif_remove_ext_callback
.extern _pbuf_free_ooseq
.extern _pbuf_alloc
.extern _pbuf_alloc_reference
.extern _pbuf_alloced_custom
.extern _pbuf_realloc
.extern _pbuf_header
.extern _pbuf_header_force
.extern _pbuf_add_header
.extern _pbuf_add_header_force
.extern _pbuf_remove_header
.extern _pbuf_free_header
.extern _pbuf_ref
.extern _pbuf_free
.extern _pbuf_clen
.extern _pbuf_cat
.extern _pbuf_chain
.extern _pbuf_dechain
.extern _pbuf_copy
.extern _pbuf_copy_partial_pbuf
.extern _pbuf_copy_partial
.extern _pbuf_get_contiguous
.extern _pbuf_take
.extern _pbuf_take_at
.extern _pbuf_skip
.extern _pbuf_coalesce
.extern _pbuf_clone
.extern _pbuf_get_at
.extern _pbuf_try_get_at
.extern _pbuf_put_at
.extern _pbuf_memcmp
.extern _pbuf_memfind
.extern _pbuf_strstr
.extern _raw_new
.extern _raw_new_ip_type
.extern _raw_remove
.extern _raw_bind
.extern _raw_bind_netif
.extern _raw_connect
.extern _raw_disconnect
.extern _raw_sendto
.extern _raw_sendto_if_src
.extern _raw_send
.extern _raw_recv
.extern _lwip_sntp_set_timezone_offset
.extern _lwip_sntp_set_dst_enabled
.extern _lwip_sntp_set_time
.extern _lwip_sntp_reset_flag
.extern _lwip_sntp_time_was_set
.extern _lwip_sntp_get_unix_time
.extern _sys_timeout
.extern _sys_untimeout
.extern _tcp_new
.extern _tcp_new_ip_type
.extern _tcp_arg
.extern _tcp_recv
.extern _tcp_sent
.extern _tcp_err
.extern _tcp_accept
.extern _tcp_poll
.extern _tcp_backlog_delayed
.extern _tcp_backlog_accepted
.extern _tcp_recved
.extern _tcp_bind
.extern _tcp_bind_netif
.extern _tcp_connect
.extern _tcp_listen_with_backlog_and_err
.extern _tcp_listen_with_backlog
.extern _tcp_abort
.extern _tcp_close
.extern _tcp_shutdown
.extern _tcp_write
.extern _tcp_setprio
.extern _tcp_output
.extern _tcp_tcp_get_tcp_addrinfo
.extern _udp_new
.extern _udp_new_ip_type
.extern _udp_remove
.extern _udp_bind
.extern _udp_bind_netif
.extern _udp_connect
.extern _udp_disconnect
.extern _udp_recv
.extern _udp_sendto_if
.extern _udp_sendto_if_src
.extern _udp_sendto
.extern _udp_send
.extern _udp_input
.extern _udp_netif_ip_addr_changed
.extern _ethernet_input
.extern _ethernet_output
.extern _eth_get_interfaces
.extern _eth_usb_event_callback
.extern _tls_x25519_publickey
.extern _tls_x25519_secret

_fn_exports_table:
    db 'L','W','I','P','T','B'    ; magic
    d24 375    ; entry count

; --- src/lwIP.c ---
    d24 _lwip_start

; --- src/core/lwip_runtime.c ---
    d24 _lwip_init_runtime_internal

; --- src/lwIP.c ---
    d24 _lwip_poll_network_events
    d24 _lwip_conn_create
    d24 _lwip_conn_destroy
    d24 _lwip_conn_connect
    d24 _lwip_conn_write
    d24 _lwip_conn_recved
    d24 _lwip_conn_shutdown
    d24 _lwip_conn_close
    d24 _lwip_conn_abort
    d24 _lwip_conn_set_arg
    d24 _lwip_conn_set_connected
    d24 _lwip_conn_set_recv
    d24 _lwip_conn_set_sent
    d24 _lwip_conn_set_err
    d24 _lwip_conn_set_poll
    d24 _lwip_conn_set_closed

; --- src/tls/core/aes.c ---
    d24 _tls_aes_init
    d24 _tls_aes_ccm_init
    d24 _tls_aes_ccm_encrypt
    d24 _tls_aes_ccm_decrypt
    d24 _tls_aes_update_aad
    d24 _tls_aes_encrypt
    d24 _tls_aes_update_ciphertext
    d24 _tls_aes_digest
    d24 _tls_aes_decrypt
    d24 _tls_aes_verify

; --- src/tls/core/asn1.c ---
    d24 _tls_asn1_cursor_init
    d24 _tls_asn1_next
    d24 _tls_asn1_child_cursor
    d24 _tls_asn1_tag_number
    d24 _tls_asn1_tag_class
    d24 _tls_asn1_tag_constructed

; --- src/tls/core/base64.c ---
    d24 _tls_base64_encode
    d24 _tls_base64_decode

; --- src/tls/core/bytes.s ---
    d24 _tls_bytes_compare

; --- src/tls/core/bytes.c ---
    d24 _tls_secure_memzero

; --- src/tls/core/sha256.s ---
    d24 _tls_sha256_init
    d24 _tls_sha256_update
    d24 _tls_sha256_digest

; --- src/tls/core/hash.c ---
    d24 _tls_hash_context_init
    d24 _tls_hash_update
    d24 _tls_hash_digest
    d24 _tls_mgf1

; --- src/tls/core/hkdf.c ---
    d24 _tls_hkdf_extract
    d24 _tls_hkdf_expand
    d24 _tls_hkdf_expand_label
    d24 _tls_derive_secret

; --- src/tls/core/hmac.c ---
    d24 _tls_hmac_context_init
    d24 _tls_hmac_update
    d24 _tls_hmac_digest

; --- src/tls/core/keyobject.c ---
    d24 _tls_keyobject_import_private
    d24 _tls_keyobject_import_public
    d24 _tls_keyobject_import_certificate

; --- src/tls/core/x509.c ---
    d24 _tls_x509_has_required_ca_constraints

; --- src/tls/core/keyobject.c ---
    d24 _tls_keyobject_destroy

; --- src/tls/core/passwords.c ---
    d24 _tls_pbkdf2

; --- src/tls/core/pkcs8.c ---
    d24 _tls_pkcs8_strerror
    d24 _tls_pkcs8_import
    d24 _tls_pkcs8_import_private
    d24 _tls_pkcs8_import_public
    d24 _tls_pkcs8_object_import_private
    d24 _tls_pkcs8_object_import_public
    d24 _tls_pkcs8_object_destroy

; --- src/tls/core/random.s ---
    d24 _tls_random_init_entropy
    d24 _tls_random
    d24 _tls_random_bytes

; --- src/tls/core/random.c ---
    d24 _tls_rng_healthcheck
    d24 _tls_request_random_bytes
    d24 _tls_rng_is_busy

; --- src/tls/core/rsa.c ---
    d24 _tls_rsa_encode_oaep
    d24 _tls_rsa_decode_oaep
    d24 _tls_rsa_encrypt
    d24 _tls_rsa_decrypt_signature
    d24 _tls_rsa_pss_verify

; --- src/tls/core/truststore.c ---
    d24 _tls_truststore_init
    d24 _tls_truststore_lookup

; --- src/tls/core/x509.c ---
    d24 _tls_x509_has_valid_constraints
    d24 _tls_x509_parse_certificate
    d24 _tls_x509_import_and_parse_certificate
    d24 _tls_x509_import_certificate
    d24 _tls_x509_object_destroy

; --- src/core/ipv4/acd.c ---
    d24 _acd_add
    d24 _acd_remove
    d24 _acd_start
    d24 _acd_stop
    d24 _acd_arp_reply
    d24 _acd_network_changed_link_down
    d24 _acd_netif_ip_addr_changed

; --- src/core/altcp.c ---
    d24 _altcp_new
    d24 _altcp_new_ip6
    d24 _altcp_new_ip_type
    d24 _altcp_arg
    d24 _altcp_accept
    d24 _altcp_recv
    d24 _altcp_sent
    d24 _altcp_poll
    d24 _altcp_err
    d24 _altcp_recved
    d24 _altcp_bind
    d24 _altcp_connect
    d24 _altcp_listen_with_backlog_and_err
    d24 _altcp_abort
    d24 _altcp_close
    d24 _altcp_shutdown
    d24 _altcp_write
    d24 _altcp_output
    d24 _altcp_mss
    d24 _altcp_sndbuf
    d24 _altcp_sndqueuelen
    d24 _altcp_nagle_disable
    d24 _altcp_nagle_enable
    d24 _altcp_nagle_disabled
    d24 _altcp_setprio
    d24 _altcp_get_tcp_addrinfo
    d24 _altcp_get_ip
    d24 _altcp_get_port

; --- src/apps/altcp_tls/altcp_tls_ce.c ---
    d24 _altcp_tls_create_config_server
    d24 _altcp_tls_config_server_add_privkey_cert
    d24 _altcp_tls_create_config_server_privkey_cert
    d24 _altcp_tls_create_config_client
    d24 _altcp_tls_create_config_client_2wayauth
    d24 _altcp_tls_configure_alpn_protocols
    d24 _altcp_tls_free_config
    d24 _altcp_tls_wrap

; --- src/core/altcp_alloc.c ---
    d24 _altcp_tls_new
    d24 _altcp_tls_alloc

; --- src/core/ipv4/autoip.c ---
    d24 _autoip_set_struct
    d24 _autoip_remove_struct
    d24 _autoip_start
    d24 _autoip_stop
    d24 _autoip_network_changed_link_up
    d24 _autoip_network_changed_link_down
    d24 _autoip_supplied_address
    d24 _autoip_accept_packet

; --- src/core/def.c ---
    d24 _lwip_htons
    d24 _lwip_htonl
    d24 _lwip_itoa
    d24 _lwip_strnicmp
    d24 _lwip_stricmp
    d24 _lwip_strnstr
    d24 _lwip_strnistr
    d24 _lwip_memcmp_consttime

; --- src/core/ipv4/dhcp.c ---
    d24 _dhcp_set_struct
    d24 _dhcp_cleanup
    d24 _dhcp_start
    d24 _dhcp_renew
    d24 _dhcp_release
    d24 _dhcp_stop
    d24 _dhcp_release_and_stop
    d24 _dhcp_inform
    d24 _dhcp_network_changed_link_up
    d24 _dhcp_supplied_address

; --- src/core/dns.c ---
    d24 _dns_setserver
    d24 _dns_getserver
    d24 _dns_gethostbyname
    d24 _dns_gethostbyname_addrtype

; --- src/core/ipv4/etharp.c ---
    d24 _etharp_find_addr
    d24 _etharp_get_entry
    d24 _etharp_output
    d24 _etharp_query
    d24 _etharp_request
    d24 _etharp_cleanup_netif
    d24 _etharp_acd_probe
    d24 _etharp_acd_announce
    d24 _etharp_input

; --- src/core/ipv4/icmp.c ---
    d24 _icmp_input
    d24 _icmp_dest_unreach
    d24 _icmp_time_exceeded

; --- src/core/ipv6/icmp6.c ---
    d24 _icmp6_input
    d24 _icmp6_dest_unreach
    d24 _icmp6_packet_too_big
    d24 _icmp6_time_exceeded
    d24 _icmp6_time_exceeded_with_addrs
    d24 _icmp6_param_problem

; --- src/core/ipv4/igmp.c ---
    d24 _igmp_start
    d24 _igmp_stop
    d24 _igmp_report_groups
    d24 _igmp_lookfor_group
    d24 _igmp_input
    d24 _igmp_joingroup
    d24 _igmp_joingroup_netif
    d24 _igmp_leavegroup
    d24 _igmp_leavegroup_netif

; --- src/core/inet_chksum.c ---
    d24 _inet_chksum
    d24 _inet_chksum_pbuf
    d24 _inet_chksum_pseudo
    d24 _inet_chksum_pseudo_partial
    d24 _ip6_chksum_pseudo
    d24 _ip6_chksum_pseudo_partial
    d24 _ip_chksum_pseudo
    d24 _ip_chksum_pseudo_partial

; --- src/core/init.c ---
    d24 _lwip_init

; --- src/core/ip.c ---
    d24 _ip_input

; --- src/core/ipv4/ip4.c ---
    d24 _ip4_route
    d24 _ip4_input
    d24 _ip4_output
    d24 _ip4_output_if
    d24 _ip4_output_if_src
    d24 _ip4_output_if_opt
    d24 _ip4_output_if_opt_src
    d24 _ip4_set_default_multicast_netif

; --- src/core/ipv4/ip4_addr.c ---
    d24 _ip4_addr_isbroadcast_u32
    d24 _ip4_addr_netmask_valid
    d24 _ipaddr_addr
    d24 _ip4addr_aton
    d24 _ip4addr_ntoa
    d24 _ip4addr_ntoa_r

; --- src/core/ipv4/ip4_frag.c ---
    d24 _ip4_reass
    d24 _ip4_frag

; --- src/core/ipv6/ip6.c ---
    d24 _ip6_route
    d24 _ip6_select_source_address
    d24 _ip6_input
    d24 _ip6_output
    d24 _ip6_output_if
    d24 _ip6_output_if_src
    d24 _ip6_options_add_hbh_ra

; --- src/core/ipv6/ip6_addr.c ---
    d24 _ip6addr_aton
    d24 _ip6addr_ntoa
    d24 _ip6addr_ntoa_r

; --- src/core/ipv6/ip6_frag.c ---
    d24 _ip6_reass
    d24 _ip6_frag

; --- src/core/ip.c ---
    d24 _ipaddr_ntoa
    d24 _ipaddr_ntoa_r
    d24 _ipaddr_aton

; --- src/core/mem.c ---
    d24 _mem_trim
    d24 _mem_malloc
    d24 _mem_calloc
    d24 _mem_free

; --- src/core/memp.c ---
    d24 _memp_malloc
    d24 _memp_free

; --- src/core/ipv6/mld6.c ---
    d24 _mld6_stop
    d24 _mld6_report_groups
    d24 _mld6_lookfor_group
    d24 _mld6_input
    d24 _mld6_joingroup
    d24 _mld6_joingroup_netif
    d24 _mld6_leavegroup
    d24 _mld6_leavegroup_netif

; --- src/core/ipv6/nd6.c ---
    d24 _nd6_input
    d24 _nd6_clear_destination_cache
    d24 _nd6_find_route
    d24 _nd6_get_next_hop_addr_or_queue
    d24 _nd6_get_destination_mtu
    d24 _nd6_reachability_hint
    d24 _nd6_cleanup_netif
    d24 _nd6_adjust_mld_membership
    d24 _nd6_restart_netif

; --- src/core/netif.c ---
    d24 _netif_alloc_client_data_id
    d24 _netif_add_noaddr
    d24 _netif_add
    d24 _netif_set_addr
    d24 _netif_remove
    d24 _netif_find
    d24 _netif_set_default
    d24 _netif_set_ipaddr
    d24 _netif_set_netmask
    d24 _netif_set_gw
    d24 _netif_set_up
    d24 _netif_set_down
    d24 _netif_set_status_callback
    d24 _netif_set_remove_callback
    d24 _netif_set_link_up
    d24 _netif_set_link_down
    d24 _netif_set_link_callback
    d24 _netif_loop_output
    d24 _netif_poll
    d24 _netif_poll_all
    d24 _netif_input
    d24 _netif_ip6_addr_set
    d24 _netif_ip6_addr_set_parts
    d24 _netif_ip6_addr_set_state
    d24 _netif_get_ip6_addr_match
    d24 _netif_create_ip6_linklocal_address
    d24 _netif_add_ip6_address
    d24 _netif_name_to_index
    d24 _netif_index_to_name
    d24 _netif_get_by_index
    d24 _netif_add_ext_callback
    d24 _netif_remove_ext_callback

; --- src/core/pbuf.c ---
    d24 _pbuf_free_ooseq
    d24 _pbuf_alloc
    d24 _pbuf_alloc_reference
    d24 _pbuf_alloced_custom
    d24 _pbuf_realloc
    d24 _pbuf_header
    d24 _pbuf_header_force
    d24 _pbuf_add_header
    d24 _pbuf_add_header_force
    d24 _pbuf_remove_header
    d24 _pbuf_free_header
    d24 _pbuf_ref
    d24 _pbuf_free
    d24 _pbuf_clen
    d24 _pbuf_cat
    d24 _pbuf_chain
    d24 _pbuf_dechain
    d24 _pbuf_copy
    d24 _pbuf_copy_partial_pbuf
    d24 _pbuf_copy_partial
    d24 _pbuf_get_contiguous
    d24 _pbuf_take
    d24 _pbuf_take_at
    d24 _pbuf_skip
    d24 _pbuf_coalesce
    d24 _pbuf_clone
    d24 _pbuf_get_at
    d24 _pbuf_try_get_at
    d24 _pbuf_put_at
    d24 _pbuf_memcmp
    d24 _pbuf_memfind
    d24 _pbuf_strstr

; --- src/core/raw.c ---
    d24 _raw_new
    d24 _raw_new_ip_type
    d24 _raw_remove
    d24 _raw_bind
    d24 _raw_bind_netif
    d24 _raw_connect
    d24 _raw_disconnect
    d24 _raw_sendto
    d24 _raw_sendto_if_src
    d24 _raw_send
    d24 _raw_recv

; --- src/core/sntp_time.c ---
    d24 _lwip_sntp_set_timezone_offset
    d24 _lwip_sntp_set_dst_enabled
    d24 _lwip_sntp_set_time
    d24 _lwip_sntp_reset_flag
    d24 _lwip_sntp_time_was_set
    d24 _lwip_sntp_get_unix_time

; --- src/core/timeouts.c ---
    d24 _sys_timeout
    d24 _sys_untimeout

; --- src/core/tcp.c ---
    d24 _tcp_new
    d24 _tcp_new_ip_type
    d24 _tcp_arg
    d24 _tcp_recv
    d24 _tcp_sent
    d24 _tcp_err
    d24 _tcp_accept
    d24 _tcp_poll
    d24 _tcp_backlog_delayed
    d24 _tcp_backlog_accepted
    d24 _tcp_recved
    d24 _tcp_bind
    d24 _tcp_bind_netif
    d24 _tcp_connect
    d24 _tcp_listen_with_backlog_and_err
    d24 _tcp_listen_with_backlog
    d24 _tcp_abort
    d24 _tcp_close
    d24 _tcp_shutdown

; --- src/core/tcp_out.c ---
    d24 _tcp_write

; --- src/core/tcp.c ---
    d24 _tcp_setprio

; --- src/core/tcp_out.c ---
    d24 _tcp_output

; --- src/core/tcp.c ---
    d24 _tcp_tcp_get_tcp_addrinfo

; --- src/core/udp.c ---
    d24 _udp_new
    d24 _udp_new_ip_type
    d24 _udp_remove
    d24 _udp_bind
    d24 _udp_bind_netif
    d24 _udp_connect
    d24 _udp_disconnect
    d24 _udp_recv
    d24 _udp_sendto_if
    d24 _udp_sendto_if_src
    d24 _udp_sendto
    d24 _udp_send
    d24 _udp_input
    d24 _udp_netif_ip_addr_changed

; --- src/netif/ethernet.c ---
    d24 _ethernet_input
    d24 _ethernet_output

; --- src/drivers/usb_ethernet.c ---
    d24 _eth_get_interfaces
    d24 _eth_usb_event_callback

; --- src/tls/contrib/x25519/src/x25519.s ---
    d24 _tls_x25519_publickey
    d24 _tls_x25519_secret
